# Generated by Django 6.1 on 2026-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_lodge'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='building_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
