# Generated by Django 6.1 on 2026-08-24 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='service_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='billing.serviceitem'),
        ),
    ]
