# Generated by Django 6.1 on 2026-08-26 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_salarypayment'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='lodge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='tenants.lodge'),
        ),
    ]
