# Generated by Django 6.1 on 2026-08-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_serviceitem_lodge'),
        ('tenants', '0002_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='lodge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tenants.lodge'),
            preserve_default=False,
        ),
    ]
