# Generated by Django 6.1 on 2026-08-27 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_expense_lodge'),
        ('tenants', '0002_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='lodge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='tenants.lodge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
