# Generated by Django 6.1 on 2026-08-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_expensecategory_lodge_alter_expensecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
