# Generated by Django 6.1 on 2026-08-29 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_staff_email_staff_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='employment_date',
            field=models.DateField(default=datetime.date(2026, 8, 29)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='employment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
