# Generated by Django 6.1 on 2026-08-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_staff_employment_date_staff_employment_end_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salarypayment',
            constraint=models.UniqueConstraint(fields=('staff', 'salary_month'), name='unique_staff_salary_month'),
        ),
    ]
