# Generated by Django 5.2.3 on 2026-09-30 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_payment_recorded_by'),
        ('tenants', '0002_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_walk_in_orders', to=settings.AUTH_USER_MODEL)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_in_orders', to='tenants.lodge')),
            ],
        ),
        migrations.CreateModel(
            name='WalkInOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.walkinorder')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='walk_in_order_items', to='billing.serviceitem')),
            ],
        ),
        migrations.CreateModel(
            name='WalkInPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('POS', 'POS'), ('Other', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.walkinorder')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_walk_in_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
