# Generated by Django 6.1 on 2026-08-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_checked_in_at_reservation_checked_out_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
