# Generated by Django 6.1 on 2026-08-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_room_rate'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='lodge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tenants.lodge'),
        ),
    ]
