# Generated by Django 5.2.3 on 2026-09-29 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_lodge'),
        ('tenants', '0002_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='short_rest_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='short_rest_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='stay_type',
            field=models.CharField(choices=[('Overnight', 'Overnight'), ('Short Rest', 'Short Rest')], default='Overnight', max_length=20),
        ),
        migrations.CreateModel(
            name='ShortRestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration_hours', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_rest_packages', to='tenants.lodge')),
            ],
            options={
                'ordering': ['duration_hours', 'name'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='short_rest_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.shortrestpackage'),
        ),
    ]
