# Generated by Django 5.2.3 on 2026-09-29 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservation_short_rest_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortrestpackage',
            name='duration_hours',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
