# Generated by Django 5.2.3 on 2026-10-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_shortrestpackage_duration_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Checked In', 'Checked In'), ('Checked Out', 'Checked Out'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Reserved', max_length=20),
        ),
    ]
