# Generated by Django 5.2.3 on 2026-09-22 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0002_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('CHECK_IN', 'Checked In'), ('CHECK_OUT', 'Checked Out'), ('CANCEL', 'Cancelled'), ('MARK_AVAILABLE', 'Marked Available'), ('ACTIVATE', 'Activated'), ('DEACTIVATE', 'Deactivated'), ('ROLE_CHANGE', 'Role Changed')], max_length=30)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('lodge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.lodge')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lodge', '-created_at'], name='audit_lodge_created_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_created_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_object_idx')],
            },
        ),
    ]
