# Generated by Django 5.2.3 on 2026-10-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('CHECK_IN', 'Checked In'), ('CHECK_OUT', 'Checked Out'), ('CANCEL', 'Cancelled'), ('NO_SHOW', 'Marked No Show'), ('MARK_AVAILABLE', 'Marked Available'), ('ACTIVATE', 'Activated'), ('DEACTIVATE', 'Deactivated'), ('ROLE_CHANGE', 'Role Changed')], max_length=30),
        ),
    ]
